### ISSUE TITLE
Any chance of an update for the latest Beta site?

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/fcc-vagrant#1]
I believe some of the requirements have changed for the latest beta.  Any chance of an update?

**Comment by BerkeleyTrue** [comment]
This repo is not currently maintained. Would you be interested in taking it over?

**Comment by SaintPeter** [comment]
Maybe.  I'm a vagrant novice.

**Comment by mikemimik** [comment]
The repo has been updated recently. "All is well on the wester front."
