### ISSUE TITLE
Vagrant Provision Fails due to missing fccmodule class

### ISSUE THREAD

**Issue by pmbenjamin** [FreeCodeCamp/fcc-vagrant#5]
Vagrant version 1.8.1
Virtualbox version 5.0.10

When issuing `vagrant provision` command, it errs with message:
```
==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class fccmodule at /tmp/vagrant-puppet/manifests-24beb1eefd2a9045c51ca95f58c32026/main.pp:33 on node freecodecamp.dev
==> default: Wrapped exception:
==> default: Could not find declared class fccmodule
==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class fccmodule at /tmp/vagrant-puppet/manifests-24beb1eefd2a9045c51ca95f58c32026/main.pp:33 on node freecodecamp.dev
```

I verified that `fccmodule` directory is indeed empty in `fcc-vagrant/provision/puppet/modules/fccmodule` although the fcc-vagrant repository includes `fccmodule` as a submodule.

**Comment by pmbenjamin** [comment]
I've been able to hack my way through it by manually adding fccmodule submodule and nodejs submodule, but perhaps these steps should be added to the README.md if submodule files do not get downloaded by default.

**Comment by mikemimik** [comment]
Hey there @pmbenjamin could you double check that you are on the most up-to-date commit from this branch? or on [tag v0.5.5](https://github.com/FreeCodeCamp/fcc-vagrant/releases/tag/v0.5.5)

**Comment by mikemimik** [comment]
Commit: 985c679 fixes the documentation on this issue.

The problem is that I made the assumption that the submodules would get pulled down with the clone of [this](http://github.com/freecodecamp/fcc-vagrant) repos master branch.
